### ISSUE TITLE
As a user, I want projects to have due dates so I can copy projects and adjust the dates of subtasks automatically.

### ISSUE THREAD

**Issue by thequailman** [candiddev/homechart#148]
## Requirements
- [ ] Projects have due dates
- [ ] Copying a project will adjust the subtask due dates based on the project's due date

## Original request
Hello,
i really want a feature to create a Project with an Start Date and several Tasks or Subtasks with a Copy Paste Function to create one Template and use this for future Projects
when i copy and paste the Template all the Subtasks should change their Date correctly and a cool Feature would be also a calculated End Date so i have a good Overview

**Comment by root9191** [comment]
Looks good but why do not implement this in the Calendar App?
Then i can see better which tasks or Events i already have in this Week and gives me a better Overview.
Also the Events do already have an End Date. If i can make on Main Event with Subtasks for each Week i can copy and paste it to a new Date and it will be done.

**Comment by root9191** [comment]
Is it possible to view Projects in a Gant View?

**Comment by root9191** [comment]
Hello, so i just took a Look at Leantime and there i can do a Template Project and Duplicate it with automatically changing their Start and End Time. Also there is a nice Gant View so i can easy see, when the Project starts and ends.

**Comment by root9191** [comment]
Hello, so the Start Date does now change correctly when i copy the Project, but the "End Recurrence On" doesn't work. 
![Bildschirmfoto 2022-08-18 um 17 37 49](https://user-images.githubusercontent.com/47309435/185436332-1c6f3da2-e970-4b59-8542-c8007b2c56b4.png)

As you can see, the Project is still active and recurring. Is there a way to make a Project Template with some Information Start and End Date to duplicate?
