### ISSUE TITLE
As a user, I want UK holidays in Homechart so I can schedule events around them

### ISSUE THREAD

**Issue by thequailman** [candiddev/homechart#185]
## Requirements
- [ ] Add UK Holidays:  https://www.gov.uk/bank-holidays

_Originally posted by @chrisbensch in https://github.com/candiddev/homechart/discussions/184#discussioncomment-3813781_

**Comment by sharrken** [comment]
There is a UK Government JSON API for Bank Holidays available:

https://www.api.gov.uk/gds/bank-holidays/#bank-holidays
