### ISSUE TITLE
As a user, I want to copy projects and update tasks due dates so I can have templated projects

### ISSUE THREAD

**Issue by thequailman** [candiddev/homechart#62]
Could you say, when it will be possible to Copy Projects or Tasks with changing their Subtasks?

_Originally posted by @root9191 in https://github.com/candiddev/homechart/discussions/57#discussioncomment-2050656_

**Comment by root9191** [comment]
Hello, could you say when this will work?

**Comment by thequailman** [comment]
It's tentatively scheduled to be part of the April release (v2022.04) but it may slip to May (v2022.05)

**Comment by thequailman** [comment]
This ended up being easy to implement, it'll be in this month's release.

**Comment by root9191** [comment]
Hello, so the Start Date will change correctly now, but the "End Recurrence On" Date is in the Past..
Could you check this please?
I am using this Version: v2022.06.0+7fdb08d

**Comment by thequailman** [comment]
I couldn't figure out the best way to get the task dates to update.  Here are two options:

- When you go to copy the project, the form has a new field called "new task date" or something that you put in a date and it changes the due date of every task to it including their recurrence
- Use the current date as the due date
